CREATE TABLE Users (
    user_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(50) NOT NULL UNIQUE,
    password        VARCHAR2(255) NOT NULL,
    role            VARCHAR2(20) CHECK (role IN ('student', 'teacher', 'guest', 'admin')),
    admin_part_id   NUMBER,
    email           VARCHAR2(100) NOT NULL UNIQUE,
    created_at      DATE DEFAULT SYSDATE,
    last_login      DATE
);


CREATE TABLE ADMIN_DEPARTMENT (
    admin_part_id         NUMBER PRIMARY KEY,
    admin_part_name       VARCHAR2(200) NOT NULL,
    created_at            DATE DEFAULT SYSDATE,            
    last_modified         DATE DEFAULT SYSDATE   
);



CREATE TABLE Document (
    document_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title            VARCHAR2(200) NOT NULL,           
    author           VARCHAR2(100),                   
    publication_year NUMBER CHECK (publication_year BETWEEN 1000 AND 9999),
    type_id          NUMBER NOT NULL,                  
    owner_id         NUMBER,
    department_id    NUMBER,
    created_at       DATE DEFAULT SYSDATE,            
    last_modified    DATE DEFAULT SYSDATE              
);


CREATE TABLE Document_Type (
    type_id         NUMBER PRIMARY KEY,
    type_name       VARCHAR2(200) NOT NULL,
    created_at       DATE DEFAULT SYSDATE,            
    last_modified    DATE DEFAULT SYSDATE   
);


CREATE TABLE DOC_Status (
    status_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    document_id         NUMBER NOT NULL, 
    doc_status          VARCHAR2(50) DEFAULT 'available' CHECK (doc_status IN ('available', 'unavailable', 'banned')), 
    change_date            DATE
);


CREATE TABLE View_Records (
    record_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id      NUMBER NOT NULL,
    document_id  NUMBER NOT NULL,
    borrow_date  DATE DEFAULT SYSDATE,
    return_date  DATE
);


CREATE TABLE Reviews (
    review_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id         NUMBER NOT NULL,
    document_id     NUMBER NOT NULL,
    rating          NUMBER CHECK (rating BETWEEN 1 AND 5),  
    comment_content VARCHAR2(1000),
    created_at      DATE DEFAULT SYSDATE
);


CREATE TABLE Notifications (
    notification_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id             NUMBER NOT NULL,
    content             VARCHAR2(1000) NOT NULL,  -- 通知内容，最大1000字符
    classification      VARCHAR2(40) NOT NULL,
    created_at          DATE DEFAULT SYSDATE       -- 发布日期，默认为当前系统时间
);



CREATE TABLE Book_Inventory (
    inventory_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    document_id         NUMBER NOT NULL,
    total_quantity      NUMBER DEFAULT 0,
    available_quantity  NUMBER DEFAULT 0,
    damaged_quantity    NUMBER DEFAULT 0
);


COMMIT;